# Generated by Django 2.1 on 2020-05-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Record',
        ),
    ]
